Style/Documentation:
    Enabled: false

Style/LineLength:
    Max: 120

Style/MethodLength:
    Max: 50

Style/SpaceInsideHashLiteralBraces:
    EnforcedStyle: no_space

Metrics/AbcSize:
    Enabled: false

Style/CyclomaticComplexity:
    Enabled: false

Metrics/PerceivedComplexity:
    Enabled: false

Style/MultilineOperationIndentation:
    Enabled: false
