sms:
  username: 'vipswj'
  password: 'Tch123456'

security_code:
  template: '您的验证码是%{security_code} 请在三分钟内输入'
  expire: 180

aws:
  access_key_id: 'AKIAPAG2UTMB6E2ZFQTQ'
  secret_access_key: '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'

s3:
  bucket: 'image.oneplusapp.com'

cdn:
  hosts: ['http://image.oneplusapp.com/']

yunba:
  app_key: '561b7f3d860409b810e0d11a'
  secret_key: 'sec-COCArBzu3fmEReMbrxsOByddKzMEgw8f5FqYo6tmHwA4Hatl'
  api_uri: 'http://rest.yunba.io:8080'

admin:
  username: '+1'
  password: '62fb52dd1ef7dd28f5ee28e15af7fc2e'
