sms:
  username: 'vipswj'
  password: 'Tch123456'

security_code:
  template: '您的验证码是%{security_code} 请在三分钟内输入'
  expire: 180

aws:
  access_key_id: 'AKIAPAG2UTMB6E2ZFQTQ'
  secret_access_key: '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'

s3:
  development:
    bucket: 'image-dev.oneplusapp.com'
    storage_bucket: 'download.oneplusapp.com'
  staging:
    bucket: 'image-dev.oneplusapp.com'
    storage_bucket: 'download.oneplusapp.com'
  production:
    bucket: 'image.oneplusapp.com'
    storage_bucket: 'download.oneplusapp.com'

cdn:
  development:
    hosts: ['http://image-dev.oneplusapp.com/']
    storage_host: 'http://download.oneplusapp.com/'
  staging:
    hosts: ['http://image-dev.oneplusapp.com/']
    storage_host: 'http://download.oneplusapp.com/'
  production:
    hosts: ['http://image.oneplusapp.com/']
    storage_host: 'http://download.oneplusapp.com/'

leancloud:
  app_id: 'uRHAcbn8PbOthR28S6hd6ArI'
  app_key: 'HQmVcG0WJ67OiCcV2OnhiBew'
  push_uri: 'https://leancloud.cn/1.1/push'

admin:
  username: '+1'
  password: '62fb52dd1ef7dd28f5ee28e15af7fc2e'
