source 'https://ruby.taobao.org/'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'mysql2'
gem 'bcrypt'
gem 'rake'
gem 'aws-sdk', '~> 2'
gem 'rmagick'
gem 'byebug'
gem 'capistrano'
gem 'capistrano-bundler'
gem 'capistrano-rvm'
gem 'capistrano-npm'
gem 'thin'
gem 'rabl'
gem 'oj'
