default: &default
  adapter: mysql2
  pool: 50
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  port: 3306

development:
  <<: *default
  database: infection
  username: infection
  password: infection
  host: 192.168.1.122

staging:
  <<: *default
  database: infection
  username: infection
  password: infection
  host: 192.168.1.122

production:
  <<: *default
  database: plus1
  username: plus1
  password: plus1
  host: 10.10.184.210
