default: &default
  adapter: mysql2
  database: infection
  username: infection
  password: infection
  pool: 50
  timeout: 5000
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  port: 3306

development:
  <<: *default
  host: 192.168.1.122
